[package]
name = "proofs"
version = "0.1.0"
authors = ["dignifiedquire <dignifiedquire@gmail.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
filecoin-proofs = { path = "./filecoin-proofs" }
storage-proofs = { path = "./storage-proofs" }
sector-base = { path = "./sector-base" }
storage-backend = { path = "./storage-backend" }

[workspace]
members = [
  "filecoin-proofs",
  "storage-proofs",
  "sector-base",
  "storage-backend",
]

[profile.test]
opt-level = 1
